name: "01 - building blocks"

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
     	run: echo "hello world"
  echo-goodby:
    runs-on: ubuntu-latest
    steps:
      - name: fail step
        run: |
	  echo "failed"
	  exit 1
      - name: say goodbye
        run: echo "goodbye"

