name: "02 - workflow events"
  
on:
  push:
  pull_request:
  schedule: #to schedule the runs
    - cron: "*/5 * * * *"
  workflow_dispatch:  #to run manually

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "show the trigger"
        run: echo "triggered by ${{ github.event_name }}"
