name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
    echo:
        runs-on: Ubuntu-latest
        steps:
            - name: echo
              run: echo "Running when PR is opened"
