name: 06 - Contexts

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

run-name: my custom run name - ${{ inputs.debug }}

env:
    MY_SOME_VAR: "some variable"

jobs:
    echo-data:
        runs-on: Ubuntu-Latest
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "${{ github.actor }}"
                echo "run number: ${{ github.run_number }}"
                
            - name: Retrieve Variable
              run: echo "${{ vars.MY_VAR }}"

            - name: My env vars
              env:
                MY_SOME_VAR: "step variable"
              run: echo "my vars ${{ env.MY_SOME_VAR }}"
