name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            value:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: Ubuntu-Latest
        steps:
            - name: "Print when input value true"
              if: ${{ inputs.value }}
              run: echo "Input value is true"

            - name: "print when input true and from main branch"
              if: ${{ inputs.value && github.ref == 'refs/head/main' }}
              run: echo "From Main branch"

            - name: "print start-up data"
              if: ${{ github.event_name }} == "push"
              run: |
                echo "Triggered by ${{ github.event_name }}"
                echo "Runner OS is ${{ runner.os }}" 
            
            - name: "Print when triggered"
              if: ${{ github.event_name }} == "workflow_dispatch"
              run: |
                echo "Triggered by ${{ github.event_name }}"
