name: 07 - Using Expressions
run-name: 07 - expressions | value - ${{ inputs.value && 'ON' || 'OFF' }}

env:
    MY_DEFAULT_VAR: ${{ vars.MY_VAR || 'NO HELLO' }}

on:
    push:
    workflow_dispatch:
        inputs:
            value:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: Ubuntu-Latest
        steps:
            - name: "Print when input value true"
              if: ${{ inputs.value }}
              run: echo "Input value is true"

            - name: "print when input true and from main branch"
              if: ${{ inputs.value && github.ref == 'refs/head/main' }}
              run: echo "From Main branch"

            - name: "print start-up data"
              if: ${{ github.event_name }} == "push"
              run: |
                echo "Triggered by ${{ github.event_name }}"
                echo "Runner OS is ${{ runner.os }}"
                ${{ github.ref }}
            
            - name: "Print when triggered"
              if: ${{ github.event_name }} == "workflow_dispatch"
              run: |
                echo "Triggered by ${{ github.event_name }}"

            - name: "Print variable"
              run: echo ${{ env.MY_DEFAULT_VAR }}
