name: 09 - org variables

on:
    - push
    - workflow_dispatch

jobs:
    print-variables:
        runs-on: Ubuntu-Latest
        environment: my_test
        steps:
            - name: print env variable
              run: echo "${{ vars.TESTENV_VAR }}"
