name: 12 - outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                default: success
                options:
                    - success
                    - failed

env:
    GITHUB_OUTPUT: "SOME PATH"

jobs:
    build:
        runs-on: Ubuntu-latest
        steps:
            - name: print guhub_output path
              run: echo "output is ${{ env.GITHUB_OUTPUT }}"

            - name: build
              id: build
              run: echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"

        outputs:
            build-status: ${{ steps.build.outputs.status }}

    deploy:
        runs-on: Ubuntu-latest
        needs: build
        steps:
            - name: deploy only build is success
              run: |
                echo "Deploying........"
                echo "asdf ${{ needs.build.outputs.build-status }}"
              if: ${{ needs.build.outputs.build-status }}  == "success"
