name: 15 - working with metrix

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 18.x
          - 20.x
          - 21.x
        include:
          - os: ubuntu-latest
            node: 16.x
            tag: testing

    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: perform tests
        run: echo "running tests on ${{ matrix.os }} and version ${{ matrix.node }}"

      - name: fail if tag is test
        if: ${{ matrix.tag }} == 'testing'
        run: exit 1

      - name: perform testing
        run: echo "testing on ${{ matrix.os }} and version ${{ matrix.node }}"
