name: 16 - env

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

run-name: 16 | env - ${{ inputs.target-env }}
       
jobs:
  echo:
    runs-on: Ubuntu-latest
    environment: ${{ inputs.target-env }}
    steps:
      - name: echo vars
        run: |
          echo "env var: ${{ vars.MY_ENV_VALUE }}"
